"""Add evidence and method to FragmentRelationship

Revision ID: 697e7cf93ee0
Revises: 
Create Date: 2026-09-26 04:18:29.973044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697e7cf93ee0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.String(), nullable=True),
    sa.Column('recovery_job_id', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('evidence_id', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('source_engine', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=True),
    sa.Column('reconstruction_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_artifact_id'), 'artifacts', ['artifact_id'], unique=True)
    op.create_index(op.f('ix_artifacts_id'), 'artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_artifacts_recovery_job_id'), 'artifacts', ['recovery_job_id'], unique=False)
    op.create_table('execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.String(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('repository', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('input_reference', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('logs', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('output_reference', sa.String(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_logs_engine'), 'execution_logs', ['engine'], unique=False)
    op.create_index(op.f('ix_execution_logs_execution_id'), 'execution_logs', ['execution_id'], unique=True)
    op.create_index(op.f('ix_execution_logs_id'), 'execution_logs', ['id'], unique=False)
    op.create_table('fragments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fragment_id', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('evidence_id', sa.String(), nullable=True),
    sa.Column('source_engine', sa.String(), nullable=True),
    sa.Column('source_artifact', sa.String(), nullable=True),
    sa.Column('source_path', sa.String(), nullable=True),
    sa.Column('source_offset', sa.Integer(), nullable=True),
    sa.Column('source_length', sa.Integer(), nullable=True),
    sa.Column('file_offset', sa.Integer(), nullable=True),
    sa.Column('fragment_size', sa.Integer(), nullable=True),
    sa.Column('fragment_type', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('entropy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fragments_fragment_id'), 'fragments', ['fragment_id'], unique=True)
    op.create_index(op.f('ix_fragments_id'), 'fragments', ['id'], unique=False)
    op.create_index(op.f('ix_fragments_job_id'), 'fragments', ['job_id'], unique=False)
    op.create_table('recovery_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('evidence_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_jobs_case_id'), 'recovery_jobs', ['case_id'], unique=False)
    op.create_index(op.f('ix_recovery_jobs_evidence_id'), 'recovery_jobs', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_recovery_jobs_id'), 'recovery_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_jobs_job_id'), 'recovery_jobs', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_jobs_job_id'), table_name='recovery_jobs')
    op.drop_index(op.f('ix_recovery_jobs_id'), table_name='recovery_jobs')
    op.drop_index(op.f('ix_recovery_jobs_evidence_id'), table_name='recovery_jobs')
    op.drop_index(op.f('ix_recovery_jobs_case_id'), table_name='recovery_jobs')
    op.drop_table('recovery_jobs')
    op.drop_index(op.f('ix_fragments_job_id'), table_name='fragments')
    op.drop_index(op.f('ix_fragments_id'), table_name='fragments')
    op.drop_index(op.f('ix_fragments_fragment_id'), table_name='fragments')
    op.drop_table('fragments')
    op.drop_index(op.f('ix_execution_logs_id'), table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_execution_id'), table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_engine'), table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_index(op.f('ix_artifacts_recovery_job_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_artifact_id'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
